[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-cloud-aiplatform>=1.121.0",
    "requests>=2.32.5",
    "tensorflow==2.17.0",
]
